spring:
  boot:
    admin:
      client:
        url: http://localhost:2126/
server:
  port: 2120
management:
  endpoints:
    web:
      exposure:
        include: " *, refresh"
  

    
 # if we are using different port or diffrent system instead of defaul port/same system  
 # Then we could configured these properies only
 
#eureka:
 # client:
  #  service-url:
     #  default-zone: http://localhost:8761/eureka
# management:
 # zipkin:
   # tracing:
   #   endpoint: http://localhost:9411/      



 WelCome to Our Microservice Coding (Balaji)
